### ISSUE TITLE
Add list of providers to the Recommendations return JSON

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-ds#101]
We need to add the list of providers to the JSON which gets returned when the post request is made to the recommendations endpoint.

**Comment by bendevera** [comment]
We shouldn't have this part of the /recommendations route but have the web team request separately because /recommendations would be very slow if we tried to add that in then

**Comment by moviedatascience** [comment]
Awesome! 

The web team successfully called separately on their end, so closing this one out
